In [9]:
import pandas as pd
import numpy as np

In [ ]:
data = np.random.rand(4,3)

In [ ]:
data

array([[0.89299642, 0.66937357, 0.32849545],
       [0.23575591, 0.71901678, 0.70913254],
       [0.73358912, 0.57162721, 0.54244654],
       [0.49711355, 0.23603205, 0.82842978]])

In [ ]:
dataFrame = dp.DataFrame(data, columns=['a','b','c'])

In [ ]:
dataFrame

          a         b         c
0  0.892996  0.669374  0.328495
1  0.235756  0.719017  0.709133
2  0.733589  0.571627  0.542447
3  0.497114  0.236032  0.828430

In [ ]:
yeniDataFrame =  dp.DataFrame(data, index=['d','e','f','g'], columns=['a','b','c'])

In [ ]:
yeniDataFrame

          a         b         c
d  0.892996  0.669374  0.328495
e  0.235756  0.719017  0.709133
f  0.733589  0.571627  0.542447
g  0.497114  0.236032  0.828430

In [ ]:
yeniDataFrame["b"]

d    0.669374
e    0.719017
f    0.571627
g    0.236032
Name: b, dtype: float64

In [ ]:
yeniDataFrame["b"]["e"]

np.float64(0.7190167806359936)

In [ ]:
yeniDataFrame[["a","c"]]

          a         c
d  0.892996  0.328495
e  0.235756  0.709133
f  0.733589  0.542447
g  0.497114  0.828430

In [ ]:
yeniDataFrame.loc["e"]

a    0.235756
b    0.719017
c    0.709133
Name: e, dtype: float64

In [ ]:
yeniDataFrame.iloc[1]

a    0.235756
b    0.719017
c    0.709133
Name: e, dtype: float64

In [ ]:
yeniDataFrame

          a         b         c
d  0.892996  0.669374  0.328495
e  0.235756  0.719017  0.709133
f  0.733589  0.571627  0.542447
g  0.497114  0.236032  0.828430

In [ ]:
yeniDataFrame["q"] = [1,2,3,4]

In [ ]:
yeniDataFrame["w"] = yeniDataFrame["a"] + yeniDataFrame["b"]

In [ ]:
yeniDataFrame

          a         b         c  q         w
d  0.892996  0.669374  0.328495  1  1.562370
e  0.235756  0.719017  0.709133  2  0.954773
f  0.733589  0.571627  0.542447  3  1.305216
g  0.497114  0.236032  0.828430  4  0.733146

In [ ]:
yeniDataFrame.drop("q", axis=1)

          a         b         c         w
d  0.892996  0.669374  0.328495  1.562370
e  0.235756  0.719017  0.709133  0.954773
f  0.733589  0.571627  0.542447  1.305216
g  0.497114  0.236032  0.828430  0.733146

In [ ]:
yeniDataFrame.drop("e",axis=0)

          a         b         c  q         w
d  0.892996  0.669374  0.328495  1  1.562370
f  0.733589  0.571627  0.542447  3  1.305216
g  0.497114  0.236032  0.828430  4  0.733146

In [ ]:
yeniDataFrame

          a         b         c  q         w
d  0.892996  0.669374  0.328495  1  1.562370
e  0.235756  0.719017  0.709133  2  0.954773
f  0.733589  0.571627  0.542447  3  1.305216
g  0.497114  0.236032  0.828430  4  0.733146

In [ ]:
yeniDataFrame.drop("w", axis=1, inplace=True)

In [ ]:
yeniDataFrame.drop("a", axis=1,inplace=False)

          b         c
d  0.669374  0.328495
e  0.719017  0.709133
f  0.571627  0.542447
g  0.236032  0.828430

In [ ]:
yeniDataFrame

          a         b         c
d  0.892996  0.669374  0.328495
e  0.235756  0.719017  0.709133
f  0.733589  0.571627  0.542447
g  0.497114  0.236032  0.828430

In [ ]:
yeniDataFrame.loc["e"]

a    0.235756
b    0.719017
c    0.709133
Name: e, dtype: float64

In [ ]:
yeniDataFrame.loc["d","b"]

np.float64(0.669373572788098)

In [ ]:
boolData = yeniDataFrame < 0.5
boolData

       a      b      c
d  False  False   True
e   True  False  False
f  False  False  False
g   True   True  False

In [ ]:
yeniDataFrame[boolData]

          a         b         c
d       NaN       NaN  0.328495
e  0.235756       NaN       NaN
f       NaN       NaN       NaN
g  0.497114  0.236032       NaN

In [ ]:
yeniDataFrame[yeniDataFrame < 0.5]

          a         b         c
d       NaN       NaN  0.328495
e  0.235756       NaN       NaN
f       NaN       NaN       NaN
g  0.497114  0.236032       NaN

In [ ]:
yeniDataFrame["b"] > 0.5

d     True
e     True
f     True
g    False
Name: b, dtype: bool

In [ ]:
yeniDataFrame[yeniDataFrame["b"]> 0.5]

          a         b         c
d  0.892996  0.669374  0.328495
e  0.235756  0.719017  0.709133
f  0.733589  0.571627  0.542447

In [ ]:
yeniDataFrame["q"] = yeniDataFrame["a"] * yeniDataFrame["b"]
yeniDataFrame

          a         b         c         q
d  0.892996  0.669374  0.328495  0.597748
e  0.235756  0.719017  0.709133  0.169512
f  0.733589  0.571627  0.542447  0.419340
g  0.497114  0.236032  0.828430  0.117335

In [ ]:
yeniDataFrame.reset_index()

  index         a         b         c         q
0     d  0.892996  0.669374  0.328495  0.597748
1     e  0.235756  0.719017  0.709133  0.169512
2     f  0.733589  0.571627  0.542447  0.419340
3     g  0.497114  0.236032  0.828430  0.117335

In [ ]:
yeniIndex = ["AA", "BB", "CC", "DD"]

In [ ]:
yeniDataFrame["yeniIndex"] = yeniIndex
yeniDataFrame

          a         b         c         q yeniIndex
d  0.892996  0.669374  0.328495  0.597748        AA
e  0.235756  0.719017  0.709133  0.169512        BB
f  0.733589  0.571627  0.542447  0.419340        CC
g  0.497114  0.236032  0.828430  0.117335        DD

In [ ]:
yeniDataFrame.set_index("yeniIndex")

                  a         b         c         q
yeniIndex
AA         0.892996  0.669374  0.328495  0.597748
BB         0.235756  0.719017  0.709133  0.169512
CC         0.733589  0.571627  0.542447  0.419340
DD         0.497114  0.236032  0.828430  0.117335

In [ ]:
yeniDataFrame

          a         b         c         q yeniIndex
d  0.892996  0.669374  0.328495  0.597748        AA
e  0.235756  0.719017  0.709133  0.169512        BB
f  0.733589  0.571627  0.542447  0.419340        CC
g  0.497114  0.236032  0.828430  0.117335        DD

In [ ]:
yeniDataFrame.set_index("yeniIndex", inplace=True)
yeniDataFrame

                  a         b         c         q
yeniIndex
AA         0.892996  0.669374  0.328495  0.597748
BB         0.235756  0.719017  0.709133  0.169512
CC         0.733589  0.571627  0.542447  0.419340
DD         0.497114  0.236032  0.828430  0.117335

In [ ]:
yeniDataFrame.loc["BB"]

a    0.235756
b    0.719017
c    0.709133
q    0.169512
Name: BB, dtype: float64

In [2]:
ilkindexler = ["Simpson","Simpson","Simpson","South Park","South Park","South Park"]
icindexler = ["Homer","Bart","Marge","Cartman","Kenny","Kyle"]
birlesmisindex = list(zip(ilkindexler,icindexler))
birlesmisindex

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [10]:
birlesmisindex = pd.MultiIndex.from_tuples(birlesmisindex)
birlesmisindex

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [13]:
benimcizgifilmlistem = [[40,"A"],[30,"B"],[20,"C"],[10,"D"],[50,"E"],[60,"F"]]
cizgifilmelr = np.array(benimcizgifilmlistem)
cizgifilmdataFrame = pd.DataFrame(cizgifilmelr, index=birlesmisindex, columns=["Puan","Film"])
cizgifilmdataFrame

                   Puan Film
Simpson    Homer     40    A
           Bart      30    B
           Marge     20    C
South Park Cartman   10    D
           Kenny     50    E
           Kyle      60    F

In [14]:
cizgifilmdataFrame.loc["Simpson"]

      Puan Film
Homer   40    A
Bart    30    B
Marge   20    C

In [17]:
cizgifilmdataFrame.loc["South Park"].loc["Cartman"]

Puan    10
Film     D
Name: Cartman, dtype: object

In [18]:
cizgifilmdataFrame.index.names = ["Karakterler","Kişiler"]
cizgifilmdataFrame

                    Puan Film
Karakterler Kişiler
Simpson     Homer     40    A
            Bart      30    B
            Marge     20    C
South Park  Cartman   10    D
            Kenny     50    E
            Kyle      60    F