In [1]:
import pandas as pd
import numpy as np

In [2]:
sozluk1 = {
    "isim": ["ali","veli","ayşe","fatma","mehmet"],
    "spor": ["futbol","basketbol","voleybol","yüzme","tenis"],
    "kalori": [500, 400, 300, 450, 350]
}

In [5]:
dataFrame = pd.DataFrame(sozluk1,index=[0,1,2,3,4])
dataFrame

     isim       spor  kalori
0     ali     futbol     500
1    veli  basketbol     400
2    ayşe   voleybol     300
3   fatma      yüzme     450
4  mehmet      tenis     350

In [6]:
sozluk2 = {
    "isim": ["osman","levent","buse","fevzi","mustafa"],
    "spor": ["futbol","basketbol","voleybol","yüzme","tenis"],
    "kalori": [300, 300, 400, 300, 300]
}

In [7]:
dataFrame2 = pd.DataFrame(sozluk2,index=[5,6,7,8,9])
dataFrame2

      isim       spor  kalori
5    osman     futbol     300
6   levent  basketbol     300
7     buse   voleybol     400
8    fevzi      yüzme     300
9  mustafa      tenis     300

In [8]:
sozluk3 = {
    "isim": ["faruk","levent","buse","fevzi","mustafa"],
    "spor": ["futbol","basketbol","voleybol","yüzme","tenis"],
    "kalori": [300, 300, 400, 300, 300]
}

In [9]:
dataFrame3 = pd.DataFrame(sozluk3,index=[10,11,12,13,14])
dataFrame3

       isim       spor  kalori
10    faruk     futbol     300
11   levent  basketbol     300
12     buse   voleybol     400
13    fevzi      yüzme     300
14  mustafa      tenis     300

consatenation

In [11]:
pd.concat([dataFrame,dataFrame2,dataFrame3])

       isim       spor  kalori
0       ali     futbol     500
1      veli  basketbol     400
2      ayşe   voleybol     300
3     fatma      yüzme     450
4    mehmet      tenis     350
5     osman     futbol     300
6    levent  basketbol     300
7      buse   voleybol     400
8     fevzi      yüzme     300
9   mustafa      tenis     300
10    faruk     futbol     300
11   levent  basketbol     300
12     buse   voleybol     400
13    fevzi      yüzme     300
14  mustafa      tenis     300

merge

In [28]:
mergeSozluk1 = {
    "isim": ["ali","veli","ayşe","fatma","mehmet"],
    "spor": ["futbol","basketbol","voleybol","yüzme","tenis"]
}

In [29]:
mergeSozluk2 = {
    "isim": ["ali","veli","ayşe","fatma","mehmet","mustafa"],
    "kalori": [500, 400, 300, 450, 350, 300]
    }

In [30]:
mergeDataFrame1 = pd.DataFrame(mergeSozluk1)
mergeDataFrame2 = pd.DataFrame(mergeSozluk2)

In [31]:
mergeDataFrame1

     isim       spor
0     ali     futbol
1    veli  basketbol
2    ayşe   voleybol
3   fatma      yüzme
4  mehmet      tenis

In [32]:
mergeDataFrame2

      isim  kalori
0      ali     500
1     veli     400
2     ayşe     300
3    fatma     450
4   mehmet     350
5  mustafa     300

In [33]:
pd.merge(mergeDataFrame1,mergeDataFrame2,on="isim")

     isim       spor  kalori
0     ali     futbol     500
1    veli  basketbol     400
2    ayşe   voleybol     300
3   fatma      yüzme     450
4  mehmet      tenis     350