In [15]:
import pandas as pd
import numpy as np

In [10]:
sozlukVerisi1 = {
    "istanbuk ": [20, np.nan, 30, 35, 40],
    "ankara": [np.nan, 20, 25, 30, np.nan],
    "izmir": [10, 15, 20, np.nan, 30],
    "afyon ": [5, 10, 30, 20, 25]
}
havadurumu = pd.DataFrame(sozlukVerisi1)

In [15]:
havadurumu.dropna()

   istanbuk   ankara  izmir  afyon
2       30.0    25.0   20.0      30

In [16]:
havadurumu

   istanbuk   ankara  izmir  afyon
0       20.0     NaN   10.0       5
1        NaN    20.0   15.0      10
2       30.0    25.0   20.0      30
3       35.0    30.0    NaN      20
4       40.0     NaN   30.0      25

In [17]:
havadurumu.dropna(axis=1)

   afyon
0       5
1      10
2      30
3      20
4      25

In [ ]:
yeniVeri = {
    "istanbuk ": [20, 25, 30, 35, 40],
    "ankara": [np.nan, 20, 25, 30, np.nan],
    "izmir": [10, 15, 20, np.nan, 30],
    "afyon ": [5, 10, 30, 20, 25]
}
yenidataframe = pd.DataFrame(yeniVeri)

In [ ]:
yenidataframe

   istanbuk   ankara  izmir  afyon
0         20     NaN   10.0       5
1         25    20.0   15.0      10
2         30    25.0   20.0      30
3         35    30.0    NaN      20
4         40     NaN   30.0      25

In [ ]:
yenidataframe.dropna(axis=1, thresh=2)

   istanbuk   ankara  izmir  afyon
0         20     NaN   10.0       5
1         25    20.0   15.0      10
2         30    25.0   20.0      30
3         35    30.0    NaN      20
4         40     NaN   30.0      25

In [ ]:
yenidataframe.fillna(20)

   istanbuk   ankara  izmir  afyon
0         20    20.0   10.0       5
1         25    20.0   15.0      10
2         30    25.0   20.0      30
3         35    30.0   20.0      20
4         40    20.0   30.0      25

groupby

In [16]:
yenisozlugu = {
    "departman" : ["yazılım","satış","pazarlama","yazılım","hukuk","pazarlama","yazılım","yazılım"],
    "calisanlar": ["ali","veli","ayşe","fatma","mehmet", "ayşe", "fatma", "mehmet"],
    "maas": [50000, 40000, 30000, 45000, 35000, 30000, 45000, 35000]
}

In [17]:
yenicalisanlar = pd.DataFrame(yenisozlugu)
yenicalisanlar

   departman calisanlar   maas
0    yazılım        ali  50000
1      satış       veli  40000
2  pazarlama       ayşe  30000
3    yazılım      fatma  45000
4      hukuk     mehmet  35000
5  pazarlama       ayşe  30000
6    yazılım      fatma  45000
7    yazılım     mehmet  35000

In [18]:
grupobjesi = yenicalisanlar.groupby("departman")

In [19]:
grupobjesi.count()

           calisanlar  maas
departman
hukuk               1     1
pazarlama           2     2
satış               1     1
yazılım             4     4

In [20]:
grupobjesi.mean(numeric_only=True)   # veya

              maas
departman
hukuk      35000.0
pazarlama  30000.0
satış      40000.0
yazılım    43750.0

In [21]:
grupobjesi.min()

          calisanlar   maas
departman
hukuk         mehmet  35000
pazarlama       ayşe  30000
satış           veli  40000
yazılım          ali  35000

In [22]:
grupobjesi.max()

          calisanlar   maas
departman
hukuk         mehmet  35000
pazarlama       ayşe  30000
satış           veli  40000
yazılım       mehmet  50000

In [23]:
grupobjesi.describe()

           maas                                                            \
          count     mean          std      min      25%      50%      75%
departman
hukuk       1.0  35000.0          NaN  35000.0  35000.0  35000.0  35000.0
pazarlama   2.0  30000.0     0.000000  30000.0  30000.0  30000.0  30000.0
satış       1.0  40000.0          NaN  40000.0  40000.0  40000.0  40000.0
yazılım     4.0  43750.0  6291.528696  35000.0  42500.0  45000.0  46250.0


               max
departman
hukuk      35000.0
pazarlama  30000.0
satış      40000.0
yazılım    50000.0